version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: medical_system_app_prod
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
    ports:
      - "3000:3000"
    volumes:
      - uploads:/usr/src/app/uploads
    depends_on:
      - db
    networks:
      - medical_net_prod

  db:
    image: postgres:14-alpine
    container_name: medical_system_db_prod
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical_net_prod

volumes:
  postgres_data:
  uploads:

networks:
  medical_net_prod:
    driver: bridge